name: Test
on:
  push:
    branches-ignore:
      - main
jobs:
  Test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16.2-alpine
        env:
          POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          POSTGRES_DB: ${{secrets.POSTGRES_DB}}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      redis:
        image: redis:6.2.6-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.16.1
      - name: Install PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 8.3.1
          run_install: false
      - name: Get PNPM store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - name: Setup PNPM cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm install
      - name: Run migration
        run: npx migrate
        env:
          POSTGRES_URL: ${{secrets.POSTGRES_URL}}
      - name: Run test
        run: pnpm test
        env:
          POSTGRES_URL: ${{secrets.POSTGRES_URL}}
          REDIS_URL: ${{secrets.REDIS_URL}}
